**************CD**********************

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: hello-deploy
spec:
   replicas: 2
   template:
      metadata:
        labels:
          app: hello-world
      spec:
        containers:
        - name: hello-pod
          image: shirishgund/amdocs
          ports:
          - containerPort: 8080



create service for access application:-

kubectl expose rc hello-rc --name=hello-svc --target-port=8080 --type=Nodeport

To deploy

Kubectl create -f kubernete.yml

To test:-
wget http://localhost:30175

O/P;-
Hello World
